### PR TITLE
Add maven central badges

### PR DESCRIPTION
**Pull request by ghostbuster91**

### CODE REVIEW

**Review by pawegio — COMMENTED** [review]
👍 for adding badges, but I would stand for single Maven Central badge linking to group id with all artifacts:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.elpassion.android.commons%22
... it's more readable and requires less scrolling in readme

**Comment by ghostbuster91** [comment]
Partially agree. But:
1. At some point we might want to use different version for different artifacts.
2. It is kind of standard that one bagde stands for one artifact one redirect to this artifact on particular site. I am not sure if we want to create such custom behavior. To make less scrolling we can put this badges in one line together with module name.

**Comment by pawegio** [comment]
Ok, I see your points. I hope I found a good solution so we can wrap module names:

[Maven Central](http://search.maven.org/#artifactdetails%7Ccom.elpassion.android.commons%7Cespresso%7C0.0.10%7Caar)

Badge source:
`https://img.shields.io/maven-central/v/com.elpassion.android.commons/espresso.svg?label=Espresso%20commons%20|%20maven%20central`

Docs:
https://shields.io/

**Comment by ghostbuster91** [comment]
Great, I'll use it then.

**Review by pawegio — APPROVED** [review]

**Pull request merged**
